
all: 
	ft contract import --make contracts/OCP_AutomaticDutchAuction.spp -f
	ft contract import --make contracts/OCP_ManualDutchAuction.spp -f
	ft contract import --make contracts/OCP_EnglishAuction.spp -f
	ft contract import --make contracts/OCP_ReverseEnglishAuction.spp -f
clean:
	rm -f *~ *.code *.tvm *.abi.json */*~ *.sol
